name: Python CI
on:
  push:
    branches:
      - main  # or master, adjust based on your default branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Adjust the Python version as needed
    - name: Create virtual environment
      run: python -m venv venv
    - name: Activate virtual environment
      run: source venv/bin/activate
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        pip install -r requirements.txt || echo "Failed to install dependencies"
    - name: Run tests
      run: |
        python -m pytest --verbose  # Add --verbose to get more detailed output

















