# Define the name of the GitHub Actions workflow as "Python CI"
name: Python CI
# Trigger the workflow on each push to the specified branches (main or master)
on:
  push:
    branches:
      - main  # or master, adjust based on your default branch
# Define a job named "build" to be executed on the latest version of Ubuntu
jobs:
  build:
    runs-on: ubuntu-latest
    # List of steps to be executed as part of the job
    steps:
      # Checkout the code from the repository using actions/checkout action
    - name: Checkout code
      uses: actions/checkout@v2
      # Set up the Python environment using actions/setup-python action
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Adjust the Python version as needed
      # Create a virtual environment named "venv"
    - name: Create virtual environment
      run: python -m venv venv
      # Activate the virtual environment
    - name: Activate virtual environment
      run: source venv/bin/activate
      # Update pip to the latest version
    - name: Update pip
      run: python -m pip install --upgrade pip
      # Install project dependencies from the requirements.txt file
    - name: Install dependencies
      run: |
        pip install -r requirements.txt || echo "Failed to install dependencies"
      # Run tests using pytest with verbose output and capture detailed test output
    - name: Run tests
      run: |
        python -m pytest --verbose > test_output.txt 2>&1 || echo "Tests failed"
        cat test_output.txt
