name: Python CI
on:
  push:
    branches:
      - main  # or master, adjust based on your default branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Adjust the Python version as needed
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust if you have a different requirements file
    - name: Run tests
      run: |
        python -m pytest  # Adjust the testing command based on your setup







